spring.datasource.url: jdbc:h2:mem:testdb

spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


spring:
  h2:
    console:
      enabled: true

api:
  secret-key: 2a10GEbgeGYxH6zVq2nQVziOQ55j3FnFo6xT1TWTDxx8XfPBBp89H096
  validity: 1548242589